version: '3.8'

services:
  redis-main-1:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-main-2:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-main-3:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-replica-1:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-replica-2:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-replica-3:
    image: redis:7.2
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-cluster-create:
    image: redis:7.2
    depends_on:
      - redis-main-1
      - redis-main-2
      - redis-main-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3
    command: [
        "/bin/bash", "-c",
        "echo yes | redis-cli --cluster-replicas 1 --cluster create redis-main-1:6379 redis-main-2:6379 redis-main-3:6379 redis-replica-1:6379 redis-replica-2:6379 redis-replica-3:6379"
    ]

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis-cluster-create
    environment:
      REDIS_HOSTS: local:redis-main-1:6379,local:redis-main-2:6379,local:redis-main-3:6379,local:redis-replica-1:6379,local:redis-replica-2:6379,local:redis-replica-3:6379
      STANDALONE: "true"
    ports:
      - "8085:8081"

  redisinsight-config:
    image: ellerbrock/alpine-bash-curl-ssl
    entrypoint: [ ]
    command: [
        "/bin/bash", "-c",
        "sleep 20 &&\
        curl --location --request POST 'redisinsight:8001/api/instance/' \
        --header 'Content-Type: application/json' \
                                  --data-raw '{
          \"name\": \"CLUSTER-LOCAL\",
          \"connectionType\": \"CLUSTER\",
          \"seedNodes\": [
            {
              \"host\": \"redis-main-1\",
              \"port\": 6379
            }
          ]
        }'"
    ]

  redisinsight:
    image: redislabs/redisinsight
    depends_on:
      - redis-cluster-create
      - redisinsight-config
    ports:
      - "8083:8001"